### PR TITLE
Interpolation of meteo data using Scipy RBFInterpolator

### PR DESCRIPTION
**Pull request by martinvonk**
This pull request allows for data to be interpolated using the [Scipy RBFInterpolator](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.RBFInterpolator.html#scipy.interpolate.RBFInterpolator).

The function currently implemented in `io_knmi` and is used by `EvaporationObs.from_xy(method='interpolation')` or the `ObsCollection.from_knmi(meteo_var=['EV24'], method='interpolation')`

The method is significantly slower compared for nearest station if a time series for only one location is collected. For multiple locations (of stations) the difference in computation time becomes much smaller. 

For a comparison see notebook `examples/04_interpolation.ipynb`

### CODE REVIEW

**Review by OnnoEbbens — COMMENTED** [review]
Nice work Martin! Finally had some time to look into this. I made some changes and fixed most of the errors in the tests. 

I merged the new example notebook you made with the existing example notebook with KNMI data. I think you should have a look at it if you like it this way. Also can you try to reduce the execution time of this notebook? I know that the interpolation takes more time but I think it is possible to remove some stuff while still showing the possibilities. 

Furthermore the only test that is still failing is the one running the KNMI example notebook. I think that is because you use the `%%time` code to monitor execution time. I believe when you use this, the variables in a cell are not created in memory and are therefore not accessible in other cells. However locally this is not a problem for me so I am not 100% sure.

**Comment by martinvonk** [comment]
So I removed all the IPython magic commands from the KNMI notebook but the test still fails here. When I run pytest locally there is no issue at all so I don't know what is going wrong.. 

Also the execution time of the Notebook is brought down by commenting out the last two cells.

**Comment by martinvonk** [comment]
Two other things are going wrong at the moment.

1. If you give a `startdate='1980-01-01', enddate='2022-07-21'` you get a timeseries from 1987-03-26 till 2022-07-21 no matter what. This also goes wrong in the notebook. If the startdate and enddate are both set before 1987-03-26 or after 2022-07-21 this error does not occur.

2. Some code was deleted so the ObsCollection (obtaining timeseries for multiply locations) is now very very slow. This happens because now when a timeseries is interpolated, an interpolator object has to be created for every timeseries and every timestep. Previously when multiple timeseries needed to be extracted this was done simultaneously for all locations on every timestep.

Something I'll look into but this has to be fixed before merging.

**Comment by martinvonk** [comment]
The two problems with the startdate/enddate and multiple locations are resolved right now. 

Only the tests still fail.

**Comment by OnnoEbbens** [comment]
The test are passing now. There were some problems with an outdated pinned version of pandas and a not working newest version of netCDF4. The pull request is ready to merge!

**Pull request merged**
