### PR TITLE
New release, version 0.8.0

### PR DESCRIPTION
**Pull request by OnnoEbbens**

### CODE REVIEW

**Review by dbrakenhoff — COMMENTED** [review]
I committed some minor changes here and there.

Two remaining questions:

- In example 01, hydropandas logging does not show the file name that is being read from the zipfile.
- is the warning about merge_observations not being thoroughly tested still necessary? Seems like the notebook is pretty thorough.

**Comment by OnnoEbbens** [comment]
All the test seem to pass but there is still something called 'build (3.7)' that is hanging for 3 days now. I don't even know what kind of check this is. Anybody knows what this is?

image

I will remove the warning about merge_observations not being thoroughly tested and see if the checks pass then.

**Comment by dbrakenhoff** [comment]
The Build 3.7 hanging we also saw with pastas and/or pastastore and is some weird remnant from previous gh actions tests that shouldn't be there but somehow is. It's annoying and all you seem to be able to do is ignore it and hope it disappears in future PRs...

**Comment by OnnoEbbens** [comment]
Thanks for letting me know. 

I just found out it is super confusing that I added a screenshot of the checks in a comment in a pull request 😕. So I hope this one passes and I can merge quickly.

**Comment by OnnoEbbens** [comment]
> The Build 3.7 hanging we also saw with pastas and/or pastastore and is some weird remnant from previous gh actions tests that shouldn't be there but somehow is. It's annoying and all you seem to be able to do is ignore it and hope it disappears in future PRs...

I think I found the origin of this error. If you go to the settings of the github repo -> Branches -> Branch protection rules you can see that there is still a requirement for "build (3.7)" to be passed before you are allowed to merge, even though "build (3.7)" does not exist anymore. When I removed this check the "build (3.7)" disappeared. I hope this will solve the issue for pastas and pastastore as well.

**Review by ArtesiaWater — APPROVED** [review]

**Pull request merged**
