### PR TITLE
Update repo

### PR DESCRIPTION
**Pull request by OnnoEbbens**
Add some functions to avoid using the KNMI api, see #59 

Also fix some bugs in Dino and Fews reading

### CODE REVIEW

**Comment by OnnoEbbens** [comment]
The tests fail when trying to download the .zip files using the requests package. The logs show an ssl error: `SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1091)'))`

When I use this code locally there is no problem and I don't need an SSL key.

**Comment by OnnoEbbens** [comment]
According to this [stackoverflow issue](https://stackoverflow.com/questions/58011032/docker-python-requests-results-in-dh-key-too-small-error) the problem might be the newest SSL verification in the latest Ubuntu version. I will now try with Ubuntu 18.04

**Review by dbrakenhoff — APPROVED** [review]
Can we download all KNMI station data with the new methods? Both meteorological stations (with evaporation) as well as the stations with only daily rainfall observations?

**Comment by OnnoEbbens** [comment]
Yes, only hourly rainfall is not supported yet.

**Review by dbrakenhoff — APPROVED** [review]

**Review by dbrakenhoff — APPROVED** [review]

**Review by dbrakenhoff — APPROVED** [review]

**Pull request merged**
