### PR TITLE
bug fixes

### PR DESCRIPTION
**Pull request by OnnoEbbens**
A minor update with some bug fixes for:
- BRO monitoring wells with multiple GLD's
- xlim in section plots

### CODE REVIEW

**Review by martinvonk — APPROVED** [review]
Nice additions, looks good.

What would we do without AI?
DALL·E 2023-03-31 12 39 46 - a panda studying streamflow using a computer

**Comment by martinvonk** [comment]
Hopefully the `build (3.7) Expected — Waiting for status to be reported` disappears after merging to the main branch.

**Comment by OnnoEbbens** [comment]
Unfortunately I cannot merge because the build is still running. Do you have any idea what it is and why it takes forever to complete?

**Comment by martinvonk** [comment]
See for instance https://github.com/pastas/pastas/pull/583 where an old GitHub action `Test suite for Jupyter Notebooks Expected — Waiting for status to be reported` is still failing.

**Pull request merged**
